SELECT cl.NOMBRE,cl.TELEFONO,cl.CIUDAD 
FROM CLIENTES cl 
INNER JOIN COMPRAS co 
ON cl.IDCLIENTE = co.IDCLIENTE 
INNER JOIN PRODUCTOS_COMPRAS pc 
ON co.IDCOMPRA = pc.IDCOMPRA 
WHERE co.FECHA > TO_DATE('2022-02-01', 'YYYY-MM-DD') AND cl.CIUDAD = 'Armenia' AND pc.TOTAL > 10000000