SELECT cl.NOMBRE,cl.TELEFONO,cl.CIUDAD, pc.CANTIDAD, SUM(pc.TOTAL) AS TOTAL_COMPRAS
FROM CLIENTES cl 
INNER JOIN COMPRAS co 
ON cl.IDCLIENTE = co.IDCLIENTE 
INNER JOIN PRODUCTOS_COMPRAS pc 
ON co.IDCOMPRA = pc.IDCOMPRA 
INNER JOIN PRODUCTOS pr ON pc.IDPROD = pr.IDPROD
WHERE pc > 100000000 ORDER BY TOTAL_COMPRAS DESC limit 5