SELECT cl.NOMBRE,cl.TELEFONO,cl.CIUDAD 
FROM CLIENTES cl 
INNER JOIN COMPRAS co 
ON cl.IDCLIENTE = co.IDCLIENTE 
INNER JOIN PRODUCTOS_COMPRAS pc 
ON co.IDCOMPRA = pc.IDCOMPRA 
INNER JOIN PRODUCTOS pr ON pc.IDPROD = pr.IDPROD
WHERE pr.DESCRIPCION = 'TV' AND pc.CANTIDAD > 2